name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SSH Deploy
        env:
          PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
          HOST_NAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          GIT_REPO: ${{ secrets.GIT_REPO }}

          # .env variables as block
          ENV_CONTENT: |
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_DB=${{ secrets.MYSQL_DB }}
            APP_NAME=FastAPIApp
            APP_VERSION=1.0.0
            APP_ENV=dev
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh

          # Write key to file and set proper permissions
          echo "$PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Add host to known hosts
          ssh-keyscan -H ${HOST_NAME} >> ~/.ssh/known_hosts

          # Use -T flag to disable pseudo-terminal allocation
          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${USER_NAME}@${HOST_NAME} <<EOF
            if [ ! -d "${PROJECT_PATH}/.git" ]; then
              mkdir -p \$(dirname ${PROJECT_PATH})
              git clone ${GIT_REPO} ${PROJECT_PATH}
            fi 

            cd ${PROJECT_PATH}
            git checkout main
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            
          EOF

          echo "Generating .env file"
          echo "$ENV_CONTENT" | ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} "cat > ${PROJECT_PATH}/.env"

          docker compose down
          docker compose up -d --build
